# Generated by Django 4.1.3 on 2022-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("location", models.TextField(blank=True, null=True)),
                ("metro_station", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Аптека",
                "verbose_name_plural": "Аптеки",
                "ordering": ["number"],
            },
        ),
    ]
