# Generated by Django 4.1.3 on 2022-11-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "doze",
                    models.FloatField(blank=True, null=True, verbose_name="Дозировка"),
                ),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="Количество"),
                ),
                (
                    "creator",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "receptRequired",
                    models.BooleanField(verbose_name="Необходимость рецепта"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
            options={
                "verbose_name": "Лекарство",
                "verbose_name_plural": "Лекарства",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="location",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="metro_station",
            field=models.CharField(max_length=50, verbose_name="Станция метро"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="number",
            field=models.IntegerField(verbose_name="Номер"),
        ),
    ]
