# Generated by Django 4.1.3 on 2022-11-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_pills_alter_pharmacy_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PillsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Категория"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория лекарств",
                "verbose_name_plural": "Категории лекарств",
                "ordering": ["name"],
            },
        ),
    ]
