# Generated by Django 4.1.3 on 2022-11-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_info_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pills",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.pillscategory",
                verbose_name="Категория",
            ),
        ),
    ]
