# Generated by Django 4.1.3 on 2022-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_info_pharmacy_info_pills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="info",
            options={
                "ordering": ["-id"],
                "verbose_name": "Информация о наличии",
                "verbose_name_plural": "Информация о наличии",
            },
        ),
        migrations.AlterField(
            model_name="info",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
